# Change these first
owner: wynand-vanrensburg # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: AccountAPI
    check: "tcp-ping"
    url: $SECRET_URL
    port: $SECRET_PORT
  - name: Account
    url: http://$SECRET_URL:$SECRET_PORT
  - name: Github
    url: https://github.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ServiceStatusPage
  introTitle: Status Page
  introMessage: This is a service Status page
  navbar:
    - title: status
      href: /
    - title: Signify
      href: https://signify.co.za/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
